/**
 * Text normalisation shared by the data build and by answer grading (§5.3).
 *
 * Kept in lib/ so engine/ can use it without reaching outside its allowed
 * imports, and so the data pipeline slugs ids with exactly the same
 * diacritic handling the grader uses.
 */

/** NFD decompose, then drop the combining marks. "Côte" -> "Cote". */
export function stripDiacritics(input: string): string {
  return input.normalize('NFD').replace(/\p{Diacritic}/gu, '');
}

/**
 * Stable entity slug: "Côte d'Ivoire" -> "cote-d-ivoire".
 * Ids generated by this are permanent — see §3.1, "never reuse".
 */
export function slugify(input: string): string {
  return stripDiacritics(input)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}
